### ISSUE TITLE
namespace error

### ISSUE THREAD

**Issue by marceloparavisi** [KCL-Planning/rosplan_demos#20]
Hello

I'm testing the turtlebot2 demo. When i run the command below, i received the following error.

> rosrun rosplan_turtlebot2_demo turtlebot_explore.bash 
Generating waypoints.
ERROR: Service [/kcl_rosplan/rosplan_roadmap_server/create_prm] is not available.

I think the turtlebot_explore.bash has an old namespace "kcl_rosplan", since the list of topics is:
`/rosplan_roadmap_server/viz/edges
/rosplan_roadmap_server/viz/edges_array
/rosplan_roadmap_server/viz/waypoints
`

Regards,
Marcelo Paravisi

**Comment by gerardcanal** [comment]
Hi Marcelo,
We updated the rosplan_demos before Christmas and maybe due to that.
To discard potential issues, have you checked out the latest version of rosplan_demos and rosplan? Can you try to build all the workspace from scratch (delete devel and build folders) and retry with the latest versions in the repositories?  

Let me know how it goes.

Best,
Gerard

**Comment by corot** [comment]
Found the same problem. Just removing `/kcl_rosplan` from the bash scripts service calls works.

**Comment by gerardcanal** [comment]
Thanks for the info. I'll try to check on this, but feel free to submit a PR if you fixed it! :-)

**Comment by corot** [comment]
#25 
I also changed the RViz configuration to see the waypoints and move_base plans

**Comment by gerardcanal** [comment]
Fixed by #25 and #31.
